# Generated by Django 4.1.5 on 2023-01-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeDTP', models.CharField(blank=True, max_length=115, null=True)),
            ],
        ),
    ]
