# Generated by Django 4.1.5 on 2023-01-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemodel',
            name='placeDTP',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
