# Generated by Django 4.1.5 on 2023-01-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evro', '0002_alter_pagemodel_placedtp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagemodel',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pagemodel',
            name='placeDTP',
            field=models.CharField(blank=True, max_length=115, null=True),
        ),
    ]
