# Generated by Django 4.1.5 on 2023-01-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evro', '0003_pagemodel_date_alter_pagemodel_placedtp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagemodel',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
