# Generated by Django 4.1.5 on 2023-01-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evro', '0004_pagemodel_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagemodel',
            name='deaded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='quantity_tc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='victims',
            field=models.IntegerField(default=0),
        ),
    ]
