# Generated by Django 4.1.5 on 2023-01-07 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evro', '0005_pagemodel_deaded_pagemodel_quantity_tc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemodel',
            name='deaded',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='pagemodel',
            name='quantity_tc',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='pagemodel',
            name='victims',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
