# Generated by Django 4.1.5 on 2023-01-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evro', '0007_alter_pagemodel_deaded_alter_pagemodel_quantity_tc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemodel',
            name='deaded',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pagemodel',
            name='quantity_tc',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pagemodel',
            name='victims',
            field=models.IntegerField(default=0),
        ),
    ]
