# Generated by Django 4.1.5 on 2023-01-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evro', '0008_alter_pagemodel_deaded_alter_pagemodel_quantity_tc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagemodel',
            name='damage_no',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='damage_yes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='drunk_no',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='drunk_yes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='other_damage_no',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='other_damage_yes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='withesses',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
