# Generated by Django 4.1.5 on 2023-01-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evro', '0009_pagemodel_damage_no_pagemodel_damage_yes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemodel',
            name='withesses',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
