# Generated by Django 4.1.5 on 2023-01-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evro', '0010_alter_pagemodel_withesses'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagemodel',
            name='bange_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='polis_men_no',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='polis_men_yes',
            field=models.BooleanField(default=False),
        ),
    ]
