# Generated by Django 4.1.5 on 2023-01-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evro', '0011_pagemodel_bange_number_pagemodel_polis_men_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagemodel',
            name='adress_a',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='adress_b',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='adress_driver_a',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='adress_driver_b',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='born_data_a',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='born_data_b',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='category_a',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='category_b',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='category_date_a',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='category_date_b',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='contract_a',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='contract_b',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='damage_no_a',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='damage_no_b',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='damage_yes_a',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='damage_yes_b',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='driver_name_a',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='driver_name_b',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='driver_number_a',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='driver_number_b',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='driver_seria_a',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='driver_seria_b',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='insurer_a',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='insurer_b',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='model_a',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='model_b',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='number_tc_a',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='number_tc_b',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='number_vin_a',
            field=models.CharField(default='', max_length=17),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='number_vin_b',
            field=models.CharField(default='', max_length=17),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='owner_name_a',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='owner_name_b',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='phone_a',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='phone_b',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='polis_date_end_a',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='polis_date_end_b',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='polis_number_a',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='polis_number_b',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='polis_seria_a',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='polis_seria_b',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='tex_number_a',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='tex_number_b',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='tex_seria_a',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='tex_seria_b',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='visible_damage_a',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='visible_damage_b',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='pagemodel',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pagemodel',
            name='placeDTP',
            field=models.CharField(max_length=115),
        ),
        migrations.AlterField(
            model_name='pagemodel',
            name='time',
            field=models.TimeField(),
        ),
    ]
