# Generated by Django 4.1.5 on 2023-01-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evro', '0012_pagemodel_adress_a_pagemodel_adress_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemodel',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pagemodel',
            name='phone_b',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pagemodel',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
