# Generated by Django 4.1.5 on 2023-01-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evro', '0013_alter_pagemodel_date_alter_pagemodel_phone_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemodel',
            name='polis_number_a',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='pagemodel',
            name='polis_number_b',
            field=models.CharField(default='', max_length=10),
        ),
    ]
