# Generated by Django 4.1.5 on 2023-01-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evro', '0016_pagemodel_quantity_a_pagemodel_quantity_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagemodel',
            name='circumstances',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='transport_a',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='transport_b',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pagemodel',
            name='adress_a',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='pagemodel',
            name='adress_b',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='pagemodel',
            name='adress_driver_a',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='pagemodel',
            name='adress_driver_b',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='pagemodel',
            name='contract_a',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pagemodel',
            name='contract_b',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
