# Generated by Django 4.1.5 on 2023-01-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evro', '0017_pagemodel_circumstances_pagemodel_transport_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagemodel',
            name='managet_another',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='managet_owner',
            field=models.BooleanField(default=False),
        ),
    ]
