# Generated by Django 4.1.5 on 2023-01-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evro', '0018_pagemodel_managet_another_pagemodel_managet_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagemodel',
            name='photo_one',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='photo_two',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='pagemodel',
            name='managet_another',
            field=models.BooleanField(default=False, verbose_name='иное лицо, подущенное к управлению ТС'),
        ),
        migrations.AlterField(
            model_name='pagemodel',
            name='managet_owner',
            field=models.BooleanField(default=False, verbose_name='собственник'),
        ),
    ]
