# Generated by Django 4.1.5 on 2023-01-10 08:32

from django.db import migrations, models
import evro.models


class Migration(migrations.Migration):

    dependencies = [
        ('evro', '0019_pagemodel_photo_one_pagemodel_photo_two_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagemodel',
            name='work_auto_no',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pagemodel',
            name='work_auto_yes',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pagemodel',
            name='photo_one',
            field=models.ImageField(blank=True, null=True, upload_to=evro.models.content_file_name),
        ),
        migrations.AlterField(
            model_name='pagemodel',
            name='photo_two',
            field=models.ImageField(blank=True, null=True, upload_to=evro.models.content_file_name),
        ),
    ]
