# Generated by Django 4.1.5 on 2023-01-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evro', '0020_pagemodel_work_auto_no_pagemodel_work_auto_yes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagemodel',
            name='location',
            field=models.TextField(blank=True, max_length=274, null=True),
        ),
        migrations.AlterField(
            model_name='pagemodel',
            name='circumstances',
            field=models.TextField(blank=True, max_length=1100, null=True),
        ),
    ]
