# Generated by Django 4.1.5 on 2023-01-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evro', '0022_pagemodel_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemodel',
            name='location',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
