# Generated by Django 4.1.5 on 2023-01-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evro', '0025_alter_pagemodel_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemodel',
            name='note',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
    ]
